sudo git config --global user.name "aiur"
sudo git config --global user.email mkotlikov@gmail.com
sudo git config --global core.editor vim
sudo git config --global color.branch auto
sudo git config --global color.diff auto
sudo git config --global color.interactive auto
sudo git config --global color.status auto
sudo git config --global color.ui auto
sudo git config --global push.default current
sudo git config --global alias.st status
sudo git config --global alias.ci commit
sudo git config --global alias.br branch
sudo git config --global alias.co checkout
sudo git config --global alias.df diff
sudo git config --global alias.fe fetch
sudo git config --global alias.cp cherry-pick
sudo git config --global alias.rb rebase
sudo git config --global alias.sm submodule
sudo git config --global alias.lg 'log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative'